#!/bin/sh
set -e
PKG=vdr-addon-avahi-linker
if [ "$1" = remove ] ; then
        for f in auto.master
        do
                [ -L /etc/$f ] && rm /etc/$f
                dpkg-divert --remove --package ${PKG} --rename \
                        --divert /etc/$f.distrib /etc/$f
        done
fi
#DEBHELPER#
exit 0
