#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
   
   if ! grep -q "^/net" /etc/auto.master; then 
       echo "/net    -hosts --timeout=60" >> /etc/auto.master
   fi
   #stop avahi-mounter 2&>1 /dev/null ||:
   mkdir -p /net
   fi  

#DEBHELPER#

