#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
   dpkg-divert --package vdr-addon-avahi-linker --add --rename \
           --divert /etc/auto.master.divert /etc/auto.master
   stop avahi-mounter 2&>1 /dev/null ||:
   mkdir -p /net
   fi  

#DEBHELPER#

